### ISSUE TITLE
Getting error when trying "Create Mod Cache"

### ISSUE THREAD

**Issue by cderring** [wmtorode/MW5-SaveEditor#1]
Hi folks,
I am seeing an error when trying to scan for mods.  When I click the "Create Mod Cache" and browse to my mods folder (in my instance "F:\Program Files\Epic Games\MW5Mercs\MW5Mercs\Mods" I get the following error - Mod Scan encountered and fatal error, please consider reporting this to Jamie Wolf

So, Here I am reporting the issue.

Thanks, and please let me know what other information you need.

**Comment by wmtorode** [comment]
what mods are you using?

**Comment by IKatsu** [comment]
(bkprocessor         :_scanMods                     :168 ) Processing Mod: MercTechV2
INFO       (bkprocessor         :_scanMod                      :138 ) processing Pak: MercTechV2.pak
ERROR      (bkprocessor         :_processPakFile               :116 ) Failed to proccess asset: MI_Smoke_06a, reason: Could read FName: 0x00000707, nameIdex: 3670015
ERROR      (bkprocessor         :_processPakFile               :116 ) Failed to proccess asset: M_Dust, reason: unpack requires a buffer of 4 bytes
INFO       (bkprocessor         :_processPakFile               :123 ) Found Mech: BZK-F3_MDA
INFO       (bkprocessor         :_processPakFile               :123 ) Found Mech: KW1-LH2_MDA
INFO       (bkprocessor         :_processPakFile               :123 ) Found Mech: RGH-1A_MDA
INFO       (bkprocessor         :_processPakFile               :123 ) Found Mech: RGH-1A_MDA1
INFO       (bkprocessor         :_processPakFile               :123 ) Found Mech: STG-3G_MDA
INFO       (bkprocessor         :_processPakFile               :123 ) Found Mech: WSP-1_MDA
INFO       (bkprocessor         :_processPakFile               :123 ) Found Mech: WSP-1A_MDA
INFO       (bkprocessor         :_processPakFile               :123 ) Found Mech: WSP-2A_MDA
INFO       (bkprocessor         :_processPakFile               :123 ) Found Mech: WSP-3A_MDA
INFO       (bkprocessor         :_processPakFile               :123 ) Found Mech: WVE-6N_MDA
INFO       (bkprocessor         :_scanMods                     :168 ) Processing Mod: Mech_Bundle
INFO       (bkprocessor         :_scanMod                      :138 ) processing Pak: Mech_Bundle.pak
INFO       (bkprocessor         :_scanMods                     :168 ) Processing Mod: MercTechComp
INFO       (bkprocessor         :_scanMod                      :138 ) processing Pak: MercTechComp.pak
INFO       (bkprocessor         :_scanMods                     :168 ) Processing Mod: MW5CAB
INFO       (bkprocessor         :_scanMod                      :138 ) processing Pak: MW5CAB.pak
CRITICAL   (bkprocessor         :_scanMods                     :181 ) Unhandled mod scan exception!
CRITICAL   (bkprocessor         :_scanMods                     :183 ) Traceback (most recent call last):
CRITICAL   (bkprocessor         :_scanMods                     :183 )   File "libui\bkprocessor.py", line 170, in _scanMods
CRITICAL   (bkprocessor         :_scanMods                     :183 )   File "libui\bkprocessor.py", line 143, in _scanMod
CRITICAL   (bkprocessor         :_scanMods                     :183 )   File "libue4pak\pakfile.py", line 20, in openPak
CRITICAL   (bkprocessor         :_scanMods                     :183 )   File "libue4pak\data\pakindex.py", line 80, in readIndex
CRITICAL   (bkprocessor         :_scanMods                     :183 )   File "libue4pak\data\pakindex.py", line 100, in _readRecord
CRITICAL   (bkprocessor         :_scanMods                     :183 ) struct.error: unpack requires a buffer of 4 bytes
CRITICAL   (bkprocessor         :_scanMods                     :183 ) 

It's the community assets bundle that is breaking it.

**Comment by wmtorode** [comment]
This should be addressed in the 1.6.2 release
