### ISSUE TITLE
Mod scan issue

### ISSUE THREAD

**Issue by NorskBerserkr** [wmtorode/MW5-SaveEditor#11]
I would give more info, but the error isn't exactly descriptive... I've recently reinstalled Mechwarrior and a few mods, namely MercTech. 
![isue](https://user-images.githubusercontent.com/95052717/143498088-9faf92df-0471-4492-af05-c0139b54f7f7.png)

**Comment by iurirolho** [comment]
i also have this error while scanning for mods i got merc tech v2 tt rules ai that's about it, i assume probably its due to patch and or mod or something else idk

**Comment by wmtorode** [comment]
merctech should now successfully scan with the current release
