### ISSUE TITLE
Editor unable to open DLC4 Saves

### ISSUE THREAD

**Issue by ZeSneakyMuffin** [wmtorode/MW5-SaveEditor#21]
PGI has probably changed their save system with the DLC4 update, as no DLC4 save I have made today is able to be opened by this save editor any longer, see screenshot of error below when attempting to load any DLC4 save game, I have also attached the log file.

EDIT: The error happens in both version 1.6.1 and 1.6.2 of the editor.

![image](https://user-images.githubusercontent.com/118759134/214976399-bde9e914-7386-4f3e-96a2-79b318b0a2a6.png)
[MW5SELog.txt](https://github.com/wmtorode/MW5-SaveEditor/files/10514328/MW5SELog.txt)

**Comment by wmtorode** [comment]
fixed in latest version
