### ISSUE TITLE
New DLC. When Will You Update And Add New Item/Mechs.

### ISSUE THREAD

**Issue by CrazedGamma1721** [wmtorode/MW5-SaveEditor#23]
Hi, I'm Wondering When Exactly We Will See A New Update For The Save Editor That Will Add In Melee Weapons And The New Mechs.
Do You Think We Could Recieve A ETA On The Next Update?

**Comment by PrincessMuu-Muu** [comment]
We didn't get an update for the previous DLC either. I fear the author doesnt play MW5 anymore, but I still got hope.

**Comment by wmtorode** [comment]
I'm not able to give an ETA, I want to update it at some point but have just been too busy to get to it

**Comment by PrincessMuu-Muu** [comment]
Appreciate it! Very good to hear from you.

**Comment by Paladin69** [comment]
This is great news, thank you for continuing the project.

**Comment by wmtorode** [comment]
updated for all current DLC
