### ISSUE TITLE
Error Loading Save file

### ISSUE THREAD

**Issue by cderring** [wmtorode/MW5-SaveEditor#26]
Hello folks,
I'm getting an error when loading a saved file.  
The error message says: 
"Load Failed!
Save Data could not be loaded; double check you selected the correct file and report this issue to Jamie Wof, including the log file."

Here's my report:
[MW5SELog.txt](https://github.com/wmtorode/MW5-SaveEditor/files/12163975/MW5SELog.txt)
My PC specs are in the DxDiag log:
[DxDiag.txt](https://github.com/wmtorode/MW5-SaveEditor/files/12163984/DxDiag.txt)
Mods Installed and active:
From Steam - PilotOverhaul, Yet Another Special Variant, Yet Another Equipment Collection, Cockpit Glass, Yet Another Mechlab, Stone Rhino / Behemoth YAML, Yet Another Weapon, StarMapMouseOver_V3_07 - Logos, Classic Mech Collection YAML, YetAnotherClanMech, Savage Wolf MC-MKIV YAML, Advanced Carrer Start, MW5 Compatibility Pack, Yet Another Weapon Clan, HeatGuage, and Remove JumpShip Animation.
From Nexus - Coyotesmission, and Yet Another Clan Invasion

Please let me know if I can provide any other information.

Thanks

**Comment by wmtorode** [comment]
need a copy of a save that causes this, none of mine through the error

**Comment by wmtorode** [comment]
no save provided, but logs show this is likely fixed by 1.6.4
