### ISSUE TITLE
MercTech v2

### ISSUE THREAD

**Issue by FeRChImoNdE** [wmtorode/MW5-SaveEditor#3]
Hi there! I've encountered this error when trying to build Mod Cache with the updated MercTech v2_

`INFO       (bkprocessor         :_scanMods                     :168 ) Processing Mod: MW5CAB
INFO       (bkprocessor         :_scanMod                      :138 ) processing Pak: MW5CAB.pak
CRITICAL   (bkprocessor         :_scanMods                     :181 ) Unhandled mod scan exception!
CRITICAL   (bkprocessor         :_scanMods                     :183 ) Traceback (most recent call last):
CRITICAL   (bkprocessor         :_scanMods                     :183 )   File "libui\bkprocessor.py", line 170, in _scanMods
CRITICAL   (bkprocessor         :_scanMods                     :183 )   File "libui\bkprocessor.py", line 143, in _scanMod
CRITICAL   (bkprocessor         :_scanMods                     :183 )   File "libue4pak\pakfile.py", line 20, in openPak
CRITICAL   (bkprocessor         :_scanMods                     :183 )   File "libue4pak\data\pakindex.py", line 80, in readIndex
CRITICAL   (bkprocessor         :_scanMods                     :183 )   File "libue4pak\data\pakindex.py", line 100, in _readRecord
CRITICAL   (bkprocessor         :_scanMods                     :183 ) struct.error: unpack requires a buffer of 4 bytes
CRITICAL   (bkprocessor         :_scanMods                     :183 ) `

It seems that fails to read MW5CAB. Since it is the asset bundle mod, temporarily remove the folder does the trick, but none of the new fancy weapons or equipment show in the drop list.

Thank you for your efforts!!

**Comment by wmtorode** [comment]
Ty, I'll take a quick look at fixing this while I update for the new DLC

**Comment by jgrochoski** [comment]
Same error for me:
INFO       (bkprocessor         :_scanMod                      :138 ) processing Pak: MW5CAB.pak
CRITICAL   (bkprocessor         :_scanMods                     :181 ) Unhandled mod scan exception!
CRITICAL   (bkprocessor         :_scanMods                     :183 ) Traceback (most recent call last):
CRITICAL   (bkprocessor         :_scanMods                     :183 )   File "libui\bkprocessor.py", line 170, in _scanMods
CRITICAL   (bkprocessor         :_scanMods                     :183 )   File "libui\bkprocessor.py", line 143, in _scanMod
CRITICAL   (bkprocessor         :_scanMods                     :183 )   File "libue4pak\pakfile.py", line 20, in openPak
CRITICAL   (bkprocessor         :_scanMods                     :183 )   File "libue4pak\data\pakindex.py", line 80, in readIndex
CRITICAL   (bkprocessor         :_scanMods                     :183 )   File "libue4pak\data\pakindex.py", line 100, in _readRecord
CRITICAL   (bkprocessor         :_scanMods                     :183 ) struct.error: unpack requires a buffer of 4 bytes
CRITICAL   (bkprocessor         :_scanMods                     :183 )

**Comment by wmtorode** [comment]
should be fixed in 1.6.2
