### ISSUE TITLE
Saves not loading

### ISSUE THREAD

**Issue by Halotoker** [wmtorode/MW5-SaveEditor#33]
INFO       (mw5save             :loadSave                      :47  ) loading save: C:/Users/USER/AppData/Local/MW5Mercs/Saved/SaveGames/47BCFC2744C5B0B0239109B2E60D7369/A3C84DC54528982010BC798DD1D55530.sav
ERROR      (bkprocessor         :_loadSave                     :77  ) Failed to load save
ERROR      (bkprocessor         :_loadSave                     :79  ) Traceback (most recent call last):
ERROR      (bkprocessor         :_loadSave                     :79  )   File "libui\bkprocessor.py", line 73, in _loadSave
ERROR      (bkprocessor         :_loadSave                     :79  )   File "libmw5save\mw5save.py", line 80, in loadSave
ERROR      (bkprocessor         :_loadSave                     :79  )   File "libmw5save\timelinemodel.py", line 11, in fromBytes
ERROR      (bkprocessor         :_loadSave                     :79  )   File "libmw5save\baseitemmodel.py", line 28, in fromBytes
ERROR      (bkprocessor         :_loadSave                     :79  )   File "libmw5save\element.py", line 38, in fromBytes
ERROR      (bkprocessor         :_loadSave                     :79  )   File "libmw5save\element.py", line 18, in _propteryFactory
ERROR      (bkprocessor         :_loadSave                     :79  )   File "libmw5save\baseproperty.py", line 79, in propertyFactory
ERROR      (bkprocessor         :_loadSave                     :79  ) TypeError: No object for type: SetProperty
ERROR      (bkprocessor         :_loadSave                     :79  ) 

Has anyone found a way to fix this?

**Comment by wmtorode** [comment]
This is fixed in 1.6.4 now
