### ISSUE TITLE
Last three versions resets me back to fresh start

### ISSUE THREAD

**Issue by jmccade1973** [wmtorode/MW5-SaveEditor#34]
I started the game using the last update found on Nexus and it works great. I am at level 8 now and tried to use the latest save editors 1.6.2 - 1.6.4. All of them removes my game files from the saved game or it is corrupting them. I am not sure which.

After selecting to load the saved game it pops up with the game options and the first time player warning and scans everything which then shows empty bays and an empty cold storage.

I am modded with all of the YAML mods, career mod, and pilot overhaul mod.

I tried the latest Nexus update and it still works.

Any suggestions to what might be going on?

What logs would you need to see from me?

**Comment by SerBrynden** [comment]
Same.

**Comment by Volsung1** [comment]
Same issue

**Comment by SerBrynden** [comment]
Related to #35 and #36.

**Comment by wmtorode** [comment]
This should be fixed by 1.6.5
