### ISSUE TITLE
No tracked objectives

### ISSUE THREAD

**Issue by JoshLoke2024** [wmtorode/MW5-SaveEditor#37]
So I just got into mechwarrior 5. Whenever I try to edit a file with save editor, it seems like all the tracked objectives disappear, as do all the mechs. I just started the game though. Literally the first mission in a new campaign. Like, day 0 lol. Not running any mods. Same results for a new career.

![428622470_10159264558991268_1840868029714936596_n](https://github.com/wmtorode/MW5-SaveEditor/assets/160663404/346ba2b1-83eb-41e6-9b15-855f54e9d175)

**Comment by SerBrynden** [comment]
Related to #34, #35, and #36.

**Comment by wmtorode** [comment]
This should be fixed by 1.6.5
