### ISSUE TITLE
1.6.5 Issues (Cold Storage Capacity Miscount)

### ISSUE THREAD

**Issue by Marxon1134** [wmtorode/MW5-SaveEditor#39]
Just tested 1.6.5, the header may be 1.4.3 but definitely works with saving properly but with all the other issues which is awesome, unfortunately one new one appeared.
Cold storage now cannot be added to claiming it's "full".
Even after I removed not one not two but 5 mechs from it.
Also if dragon's gambit is DLC 5 would that mean the "Otomo" or s variants for the
MAL-MX90-S
CPLT-K2-S
HTM-26T-S
BLR-1G-S
CHR-3K-S
Should be included too?
Great job fixing the saving issue and really like the new tier selector option that trims down the menu size, along with having the cache files being generated.
Sorry to be bearer of bad news on cold storage.

**Comment by wmtorode** [comment]
please re-grab the release, somehow that was an old binary that I uploaded by mistake

**Comment by Marxon1134** [comment]
Retested multiple times.
No bugs!
