### ISSUE TITLE
New DLC 'mechs not in current Save Editor

### ISSUE THREAD

**Issue by cmdrnmartin** [wmtorode/MW5-SaveEditor#5]
Just noticed that the new 'mechs in the latest DLC are not available (or don't seem to be available) to add to the 'mech bay cold storage.  Could this be looked at for a future release?

**Comment by jimt0r** [comment]
personally been thinking about this one, looking through the "editors" content and stumbled across this \MechWarrior5Editor\MW5Mercs\Content\mechwhitelist.csv and was wondering if something like this could be used to make a mod to import the mech list for the DLC

**Comment by wmtorode** [comment]
added in 1.6.2
